### ISSUE TITLE
Model file cannot be opened for loading!

### ISSUE THREAD

**Issue by sherry975-rxi** [leonweber/nlprolog#1]
I got an the error "Model file cannot be opened for loading!" when I was running the train.py.

Can anyone please give some advice on this?

**Comment by sherry975-rxi** [comment]
I have fixed it!

**Comment by XinQuan42** [comment]
Hello! May I ask how did you fix this error?

**Comment by XinQuan42** [comment]
> I have fixed it!

Hello! May I ask how did you fix this error?
